[package]
name = "cosmic"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
freedesktop-icons = "0.2.1"
iced = { path = "../.." , features = ["cosmic_theme", "svg"] }
