/// The symbolic name of a keyboard key.
///
/// This is mostly the `KeyCode` type found in `winit`. If you are using
/// `winit`, consider enabling the `winit` feature to get conversion
/// implementations for free!
#[derive(Debug, Hash, Ord, PartialOrd, PartialEq, Eq, Clone, Copy)]
#[repr(u32)]
#[allow(missing_docs)]
pub enum KeyCode {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq
    Snapshot,
    /// Scroll Lock
    Scroll,
    /// Pause/Break key, next to Scroll lock
    Pause,

    /// `Insert`, next to Backspace
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    Backspace,
    Enter,
    Space,

    /// The "Compose" key on Linux
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,

    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,  // also called "Prior"
    NavigateBackward, // also called "Next"
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

#[cfg(feature = "winit")]
mod winit_conversion {
    use winit::event::VirtualKeyCode;

    impl From<VirtualKeyCode> for super::KeyCode {
        fn from(virtual_keycode: VirtualKeyCode) -> Self {
            match virtual_keycode {
                VirtualKeyCode::Key1 => super::KeyCode::Key1,
                VirtualKeyCode::Key2 => super::KeyCode::Key2,
                VirtualKeyCode::Key3 => super::KeyCode::Key3,
                VirtualKeyCode::Key4 => super::KeyCode::Key4,
                VirtualKeyCode::Key5 => super::KeyCode::Key5,
                VirtualKeyCode::Key6 => super::KeyCode::Key6,
                VirtualKeyCode::Key7 => super::KeyCode::Key7,
                VirtualKeyCode::Key8 => super::KeyCode::Key8,
                VirtualKeyCode::Key9 => super::KeyCode::Key9,
                VirtualKeyCode::Key0 => super::KeyCode::Key0,
                VirtualKeyCode::A => super::KeyCode::A,
                VirtualKeyCode::B => super::KeyCode::B,
                VirtualKeyCode::C => super::KeyCode::C,
                VirtualKeyCode::D => super::KeyCode::D,
                VirtualKeyCode::E => super::KeyCode::E,
                VirtualKeyCode::F => super::KeyCode::F,
                VirtualKeyCode::G => super::KeyCode::G,
                VirtualKeyCode::H => super::KeyCode::H,
                VirtualKeyCode::I => super::KeyCode::I,
                VirtualKeyCode::J => super::KeyCode::J,
                VirtualKeyCode::K => super::KeyCode::K,
                VirtualKeyCode::L => super::KeyCode::L,
                VirtualKeyCode::M => super::KeyCode::M,
                VirtualKeyCode::N => super::KeyCode::N,
                VirtualKeyCode::O => super::KeyCode::O,
                VirtualKeyCode::P => super::KeyCode::P,
                VirtualKeyCode::Q => super::KeyCode::Q,
                VirtualKeyCode::R => super::KeyCode::R,
                VirtualKeyCode::S => super::KeyCode::S,
                VirtualKeyCode::T => super::KeyCode::T,
                VirtualKeyCode::U => super::KeyCode::U,
                VirtualKeyCode::V => super::KeyCode::V,
                VirtualKeyCode::W => super::KeyCode::W,
                VirtualKeyCode::X => super::KeyCode::X,
                VirtualKeyCode::Y => super::KeyCode::Y,
                VirtualKeyCode::Z => super::KeyCode::Z,
                VirtualKeyCode::Escape => super::KeyCode::Escape,
                VirtualKeyCode::F1 => super::KeyCode::F1,
                VirtualKeyCode::F2 => super::KeyCode::F2,
                VirtualKeyCode::F3 => super::KeyCode::F3,
                VirtualKeyCode::F4 => super::KeyCode::F4,
                VirtualKeyCode::F5 => super::KeyCode::F5,
                VirtualKeyCode::F6 => super::KeyCode::F6,
                VirtualKeyCode::F7 => super::KeyCode::F7,
                VirtualKeyCode::F8 => super::KeyCode::F8,
                VirtualKeyCode::F9 => super::KeyCode::F9,
                VirtualKeyCode::F10 => super::KeyCode::F10,
                VirtualKeyCode::F11 => super::KeyCode::F11,
                VirtualKeyCode::F12 => super::KeyCode::F12,
                VirtualKeyCode::F13 => super::KeyCode::F13,
                VirtualKeyCode::F14 => super::KeyCode::F14,
                VirtualKeyCode::F15 => super::KeyCode::F15,
                VirtualKeyCode::F16 => super::KeyCode::F16,
                VirtualKeyCode::F17 => super::KeyCode::F17,
                VirtualKeyCode::F18 => super::KeyCode::F18,
                VirtualKeyCode::F19 => super::KeyCode::F19,
                VirtualKeyCode::F20 => super::KeyCode::F20,
                VirtualKeyCode::F21 => super::KeyCode::F21,
                VirtualKeyCode::F22 => super::KeyCode::F22,
                VirtualKeyCode::F23 => super::KeyCode::F23,
                VirtualKeyCode::F24 => super::KeyCode::F24,
                VirtualKeyCode::Snapshot => super::KeyCode::Snapshot,
                VirtualKeyCode::Scroll => super::KeyCode::Scroll,
                VirtualKeyCode::Pause => super::KeyCode::Pause,
                VirtualKeyCode::Insert => super::KeyCode::Insert,
                VirtualKeyCode::Home => super::KeyCode::Home,
                VirtualKeyCode::Delete => super::KeyCode::Delete,
                VirtualKeyCode::End => super::KeyCode::End,
                VirtualKeyCode::PageDown => super::KeyCode::PageDown,
                VirtualKeyCode::PageUp => super::KeyCode::PageUp,
                VirtualKeyCode::Left => super::KeyCode::Left,
                VirtualKeyCode::Up => super::KeyCode::Up,
                VirtualKeyCode::Right => super::KeyCode::Right,
                VirtualKeyCode::Down => super::KeyCode::Down,
                VirtualKeyCode::Back => super::KeyCode::Backspace,
                VirtualKeyCode::Return => super::KeyCode::Enter,
                VirtualKeyCode::Space => super::KeyCode::Space,
                VirtualKeyCode::Compose => super::KeyCode::Compose,
                VirtualKeyCode::Caret => super::KeyCode::Caret,
                VirtualKeyCode::Numlock => super::KeyCode::Numlock,
                VirtualKeyCode::Numpad0 => super::KeyCode::Numpad0,
                VirtualKeyCode::Numpad1 => super::KeyCode::Numpad1,
                VirtualKeyCode::Numpad2 => super::KeyCode::Numpad2,
                VirtualKeyCode::Numpad3 => super::KeyCode::Numpad3,
                VirtualKeyCode::Numpad4 => super::KeyCode::Numpad4,
                VirtualKeyCode::Numpad5 => super::KeyCode::Numpad5,
                VirtualKeyCode::Numpad6 => super::KeyCode::Numpad6,
                VirtualKeyCode::Numpad7 => super::KeyCode::Numpad7,
                VirtualKeyCode::Numpad8 => super::KeyCode::Numpad8,
                VirtualKeyCode::Numpad9 => super::KeyCode::Numpad9,
                VirtualKeyCode::AbntC1 => super::KeyCode::AbntC1,
                VirtualKeyCode::AbntC2 => super::KeyCode::AbntC2,
                VirtualKeyCode::Add => super::KeyCode::Add,
                VirtualKeyCode::Apostrophe => super::KeyCode::Apostrophe,
                VirtualKeyCode::Apps => super::KeyCode::Apps,
                VirtualKeyCode::At => super::KeyCode::At,
                VirtualKeyCode::Ax => super::KeyCode::Ax,
                VirtualKeyCode::Backslash => super::KeyCode::Backslash,
                VirtualKeyCode::Calculator => super::KeyCode::Calculator,
                VirtualKeyCode::Capital => super::KeyCode::Capital,
                VirtualKeyCode::Colon => super::KeyCode::Colon,
                VirtualKeyCode::Comma => super::KeyCode::Comma,
                VirtualKeyCode::Convert => super::KeyCode::Convert,
                VirtualKeyCode::Decimal => super::KeyCode::Decimal,
                VirtualKeyCode::Divide => super::KeyCode::Divide,
                VirtualKeyCode::Equals => super::KeyCode::Equals,
                VirtualKeyCode::Grave => super::KeyCode::Grave,
                VirtualKeyCode::Kana => super::KeyCode::Kana,
                VirtualKeyCode::Kanji => super::KeyCode::Kanji,
                VirtualKeyCode::LAlt => super::KeyCode::LAlt,
                VirtualKeyCode::LBracket => super::KeyCode::LBracket,
                VirtualKeyCode::LControl => super::KeyCode::LControl,
                VirtualKeyCode::LShift => super::KeyCode::LShift,
                VirtualKeyCode::LWin => super::KeyCode::LWin,
                VirtualKeyCode::Mail => super::KeyCode::Mail,
                VirtualKeyCode::MediaSelect => super::KeyCode::MediaSelect,
                VirtualKeyCode::MediaStop => super::KeyCode::MediaStop,
                VirtualKeyCode::Minus => super::KeyCode::Minus,
                VirtualKeyCode::Multiply => super::KeyCode::Multiply,
                VirtualKeyCode::Mute => super::KeyCode::Mute,
                VirtualKeyCode::MyComputer => super::KeyCode::MyComputer,
                VirtualKeyCode::NavigateForward => {
                    super::KeyCode::NavigateForward
                }
                VirtualKeyCode::NavigateBackward => {
                    super::KeyCode::NavigateBackward
                }
                VirtualKeyCode::NextTrack => super::KeyCode::NextTrack,
                VirtualKeyCode::NoConvert => super::KeyCode::NoConvert,
                VirtualKeyCode::NumpadComma => super::KeyCode::NumpadComma,
                VirtualKeyCode::NumpadEnter => super::KeyCode::NumpadEnter,
                VirtualKeyCode::NumpadEquals => super::KeyCode::NumpadEquals,
                VirtualKeyCode::OEM102 => super::KeyCode::OEM102,
                VirtualKeyCode::Period => super::KeyCode::Period,
                VirtualKeyCode::PlayPause => super::KeyCode::PlayPause,
                VirtualKeyCode::Power => super::KeyCode::Power,
                VirtualKeyCode::PrevTrack => super::KeyCode::PrevTrack,
                VirtualKeyCode::RAlt => super::KeyCode::RAlt,
                VirtualKeyCode::RBracket => super::KeyCode::RBracket,
                VirtualKeyCode::RControl => super::KeyCode::RControl,
                VirtualKeyCode::RShift => super::KeyCode::RShift,
                VirtualKeyCode::RWin => super::KeyCode::RWin,
                VirtualKeyCode::Semicolon => super::KeyCode::Semicolon,
                VirtualKeyCode::Slash => super::KeyCode::Slash,
                VirtualKeyCode::Sleep => super::KeyCode::Sleep,
                VirtualKeyCode::Stop => super::KeyCode::Stop,
                VirtualKeyCode::Subtract => super::KeyCode::Subtract,
                VirtualKeyCode::Sysrq => super::KeyCode::Sysrq,
                VirtualKeyCode::Tab => super::KeyCode::Tab,
                VirtualKeyCode::Underline => super::KeyCode::Underline,
                VirtualKeyCode::Unlabeled => super::KeyCode::Unlabeled,
                VirtualKeyCode::VolumeDown => super::KeyCode::VolumeDown,
                VirtualKeyCode::VolumeUp => super::KeyCode::VolumeUp,
                VirtualKeyCode::Wake => super::KeyCode::Wake,
                VirtualKeyCode::WebBack => super::KeyCode::WebBack,
                VirtualKeyCode::WebFavorites => super::KeyCode::WebFavorites,
                VirtualKeyCode::WebForward => super::KeyCode::WebForward,
                VirtualKeyCode::WebHome => super::KeyCode::WebHome,
                VirtualKeyCode::WebRefresh => super::KeyCode::WebRefresh,
                VirtualKeyCode::WebSearch => super::KeyCode::WebSearch,
                VirtualKeyCode::WebStop => super::KeyCode::WebStop,
                VirtualKeyCode::Yen => super::KeyCode::Yen,
                VirtualKeyCode::Copy => super::KeyCode::Copy,
                VirtualKeyCode::Paste => super::KeyCode::Paste,
                VirtualKeyCode::Cut => super::KeyCode::Cut,
            }
        }
    }
}
