[package]
name = "animations"
version = "0.1.0"
authors = ["LazyTanuki"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["debug"] }
# iced = "0.9"
iced_aw = { git = "https://github.com/iced-rs/iced_aw", branch = "main", features = ["tabs"] }
