[package]
name = "custom_menu"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
iced.features = ["custom-menu"]
iced.workspace = true
image = { workspace = true, default-features = true }
muda.workspace = true
