[package]
name = "SurrealDB_UI_example"
version = "0.1.0"
authors = ["Dave MacLeod <mithradates@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.97"
async-openai = "0.28.3"
iced = {version = "0.13.1", features = ["image"] }
mistralai-client = "0.14.0"
serde = "1.0.219"
serde_json = "1.0.140"
surrealdb = { version = "2.2.1", features = ["kv-mem"] }
tokio = "1.44.0"
ureq = "3.0.12"