[package]
name = "clock"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced.workspace = true
iced.features = ["canvas", "tokio", "debug"]
chrono = { version = "0.4", features = [ "clock" ] }
tracing-subscriber = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced.workspace = true
iced.features = ["webgl", "canvas", "tokio", "debug"]
chrono = { version = "0.4", features = [ "clock", "wasmbind" ] }
instant = { version = "0.1", features = [ "wasm-bindgen" ] }

