[package]
name = "integration_opengl"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced_glow = { path = "../../glow" }
iced_native = { path = "../../native" }
env_logger = "0.8"
glutin = "0.30.3"
glutin-winit = "0.2.2"
raw-window-handle = "0.5.0"
winit = "0.27.5"
